// Enhanced Product Database - 60+ Premium Products with Verified Images
export const ENHANCED_PRODUCTS = [
    // ==================== MEN'S COLLECTION (20 Products) ====================

    // Men's Outerwear
    {
        _id: 'men-jacket-001',
        name: 'Stealth Bomber Jacket',
        price: 5999,
        originalPrice: 8999,
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80'],
        category: 'jackets',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 45,
        isActive: true,
        rating: 4.9,
        reviews: 234,
        isNew: true,
        description: 'Premium water-resistant bomber with thermal lining and utility pockets.'
    },
    {
        _id: 'men-jacket-002',
        name: 'Urban Puffer Coat',
        price: 7499,
        originalPrice: 10999,
        images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80'],
        category: 'jackets',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Charcoal', 'Olive'],
        sizes: ['M', 'L', 'XL', 'XXL'],
        stock: 32,
        isActive: true,
        rating: 4.8,
        reviews: 187,
        description: 'Insulated puffer with down fill and windproof shell.'
    },
    {
        _id: 'men-jacket-003',
        name: 'Tech Windbreaker',
        price: 3999,
        originalPrice: 5999,
        images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80'],
        category: 'jackets',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Gray', 'Blue'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 67,
        isActive: true,
        rating: 4.7,
        reviews: 156,
        description: 'Lightweight windbreaker with breathable mesh lining.'
    },

    // Men's Shirts
    {
        _id: 'men-shirt-001',
        name: 'Oxford Button-Down',
        price: 2499,
        originalPrice: 3999,
        images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80'],
        category: 'shirts',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['White', 'Blue', 'Black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        stock: 89,
        isActive: true,
        rating: 4.6,
        reviews: 342,
        description: 'Classic Oxford shirt in premium cotton with easy-iron finish.'
    },
    {
        _id: 'men-shirt-002',
        name: 'Linen Casual Shirt',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=800&q=80'],
        category: 'shirts',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Beige', 'White', 'Light Blue'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 54,
        isActive: true,
        rating: 4.5,
        reviews: 128,
        description: 'Breathable linen shirt perfect for summer wear.'
    },
    {
        _id: 'men-shirt-003',
        name: 'Flannel Check Shirt',
        price: 2799,
        originalPrice: 4299,
        images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80'],
        category: 'shirts',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Red Check', 'Blue Check', 'Green Check'],
        sizes: ['M', 'L', 'XL'],
        stock: 43,
        isActive: true,
        rating: 4.7,
        reviews: 201,
        description: 'Soft flannel shirt with classic check pattern.'
    },

    // Men's T-Shirts
    {
        _id: 'men-tshirt-001',
        name: 'Premium Cotton Tee',
        price: 1299,
        originalPrice: 1999,
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80'],
        category: 'tshirts',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'White', 'Gray', 'Navy'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        stock: 156,
        isActive: true,
        rating: 4.8,
        reviews: 567,
        description: 'Essential crew neck tee in heavyweight cotton.'
    },
    {
        _id: 'men-tshirt-002',
        name: 'Oversized Graphic Tee',
        price: 1599,
        originalPrice: 2499,
        images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80'],
        category: 'tshirts',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'White'],
        sizes: ['M', 'L', 'XL'],
        stock: 78,
        isActive: true,
        rating: 4.6,
        reviews: 234,
        isNew: true,
        description: 'Relaxed fit tee with bold graphics.'
    },

    // Men's Pants
    {
        _id: 'men-pants-001',
        name: 'Cargo Utility Pants',
        price: 3899,
        originalPrice: 5499,
        images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80'],
        category: 'pants',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Olive', 'Khaki'],
        sizes: ['30', '32', '34', '36', '38'],
        stock: 67,
        isActive: true,
        rating: 4.9,
        reviews: 389,
        description: 'Multi-pocket cargo pants with reinforced stitching.'
    },
    {
        _id: 'men-pants-002',
        name: 'Slim Fit Chinos',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80'],
        category: 'pants',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Navy', 'Beige', 'Gray'],
        sizes: ['30', '32', '34', '36'],
        stock: 92,
        isActive: true,
        rating: 4.7,
        reviews: 445,
        description: 'Modern slim-fit chinos in stretch cotton.'
    },
    {
        _id: 'men-pants-003',
        name: 'Tech Joggers',
        price: 2499,
        originalPrice: 3999,
        images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&q=80'],
        category: 'pants',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Gray', 'Navy'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 103,
        isActive: true,
        rating: 4.8,
        reviews: 512,
        description: 'Athletic joggers with zippered pockets and tapered fit.'
    },

    // Men's Jeans
    {
        _id: 'men-jeans-001',
        name: 'Slim Fit Denim',
        price: 3499,
        originalPrice: 5499,
        images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80'],
        category: 'jeans',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Dark Blue', 'Black', 'Light Blue'],
        sizes: ['30', '32', '34', '36', '38'],
        stock: 87,
        isActive: true,
        rating: 4.7,
        reviews: 678,
        description: 'Classic slim-fit jeans in premium denim.'
    },
    {
        _id: 'men-jeans-002',
        name: 'Distressed Straight Jeans',
        price: 3999,
        originalPrice: 5999,
        images: ['https://images.unsplash.com/photo-1475178626620-a4d074967452?w=800&q=80'],
        category: 'jeans',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Blue', 'Black'],
        sizes: ['30', '32', '34', '36'],
        stock: 54,
        isActive: true,
        rating: 4.6,
        reviews: 289,
        description: 'Straight-leg jeans with subtle distressing.'
    },

    // Men's Sweaters
    {
        _id: 'men-sweater-001',
        name: 'Cable Knit Sweater',
        price: 3499,
        originalPrice: 5499,
        images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80'],
        category: 'sweaters',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Cream', 'Navy', 'Gray'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 45,
        isActive: true,
        rating: 4.8,
        reviews: 234,
        description: 'Classic cable knit in soft wool blend.'
    },
    {
        _id: 'men-sweater-002',
        name: 'Quarter-Zip Pullover',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80'],
        category: 'sweaters',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'Burgundy'],
        sizes: ['M', 'L', 'XL'],
        stock: 67,
        isActive: true,
        rating: 4.7,
        reviews: 345,
        description: 'Versatile quarter-zip in merino wool.'
    },

    // Men's Activewear
    {
        _id: 'men-active-001',
        name: 'Performance Shorts',
        price: 1899,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80'],
        category: 'activewear',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'Gray'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 123,
        isActive: true,
        rating: 4.6,
        reviews: 456,
        description: 'Moisture-wicking shorts with built-in liner.'
    },
    {
        _id: 'men-active-002',
        name: 'Training Hoodie',
        price: 3299,
        originalPrice: 4999,
        images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80'],
        category: 'activewear',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Gray', 'Navy'],
        sizes: ['M', 'L', 'XL'],
        stock: 78,
        isActive: true,
        rating: 4.8,
        reviews: 389,
        description: 'Tech fleece hoodie with thumbholes and zippered pockets.'
    },

    // Men's Footwear
    {
        _id: 'men-shoes-001',
        name: 'Urban Sneakers',
        price: 4999,
        originalPrice: 7499,
        images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80'],
        category: 'footwear',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['White', 'Black', 'Gray'],
        sizes: ['8', '9', '10', '11', '12'],
        stock: 56,
        isActive: true,
        rating: 4.9,
        reviews: 789,
        description: 'Premium leather sneakers with cushioned sole.'
    },
    {
        _id: 'men-shoes-002',
        name: 'Chelsea Boots',
        price: 6999,
        originalPrice: 9999,
        images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80'],
        category: 'footwear',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Brown'],
        sizes: ['8', '9', '10', '11'],
        stock: 34,
        isActive: true,
        rating: 4.8,
        reviews: 234,
        description: 'Classic Chelsea boots in genuine leather.'
    },

    // Men's Accessories
    {
        _id: 'men-acc-001',
        name: 'Leather Wallet',
        price: 1999,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80'],
        category: 'accessories',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Black', 'Brown'],
        sizes: ['One Size'],
        stock: 145,
        isActive: true,
        rating: 4.7,
        reviews: 567,
        description: 'Bifold wallet in full-grain leather with RFID protection.'
    },

    // ==================== WOMEN'S COLLECTION (20 Products) ====================

    // Women's Outerwear
    {
        _id: 'women-jacket-001',
        name: 'Quilted Puffer Jacket',
        price: 6999,
        originalPrice: 9999,
        images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80'],
        category: 'jackets',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Cream', 'Burgundy'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 43,
        isActive: true,
        rating: 4.9,
        reviews: 345,
        isNew: true,
        description: 'Lightweight quilted jacket with down insulation.'
    },
    {
        _id: 'women-jacket-002',
        name: 'Wool Blend Coat',
        price: 8999,
        originalPrice: 12999,
        images: ['https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800&q=80'],
        category: 'jackets',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Camel', 'Black', 'Gray'],
        sizes: ['S', 'M', 'L'],
        stock: 28,
        isActive: true,
        rating: 4.8,
        reviews: 234,
        description: 'Classic wool blend coat with belt detail.'
    },
    {
        _id: 'women-jacket-003',
        name: 'Denim Jacket',
        price: 3999,
        originalPrice: 5999,
        images: ['https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=800&q=80'],
        category: 'jackets',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Light Blue', 'Black'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        stock: 67,
        isActive: true,
        rating: 4.7,
        reviews: 456,
        description: 'Classic denim jacket with vintage wash.'
    },

    // Women's Tops
    {
        _id: 'women-top-001',
        name: 'Silk Blouse',
        price: 3499,
        originalPrice: 5499,
        images: ['https://images.unsplash.com/photo-1564257577-d18b5b6c4b7a?w=800&q=80'],
        category: 'tops',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['White', 'Blush', 'Navy'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 54,
        isActive: true,
        rating: 4.6,
        reviews: 289,
        description: 'Elegant silk blouse with button details.'
    },
    {
        _id: 'women-top-002',
        name: 'Ribbed Tank Top',
        price: 1299,
        originalPrice: 1999,
        images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80'],
        category: 'tops',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['White', 'Black', 'Beige', 'Olive'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 134,
        isActive: true,
        rating: 4.5,
        reviews: 678,
        description: 'Essential ribbed tank in soft cotton.'
    },
    {
        _id: 'women-top-003',
        name: 'Oversized Sweater',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80'],
        category: 'tops',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Cream', 'Gray', 'Camel'],
        sizes: ['S', 'M', 'L'],
        stock: 45,
        isActive: true,
        rating: 4.8,
        reviews: 345,
        description: 'Cozy oversized sweater in chunky knit.'
    },

    // Women's Dresses
    {
        _id: 'women-dress-001',
        name: 'Midi Wrap Dress',
        price: 4999,
        originalPrice: 7499,
        images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80'],
        category: 'dresses',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'Burgundy'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 38,
        isActive: true,
        rating: 4.9,
        reviews: 456,
        description: 'Elegant wrap dress with tie waist.'
    },
    {
        _id: 'women-dress-002',
        name: 'Maxi Floral Dress',
        price: 5499,
        originalPrice: 7999,
        images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80'],
        category: 'dresses',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Floral Print'],
        sizes: ['S', 'M', 'L'],
        stock: 29,
        isActive: true,
        rating: 4.7,
        reviews: 234,
        description: 'Flowing maxi dress with floral pattern.'
    },

    // Women's Bottoms
    {
        _id: 'women-pants-001',
        name: 'High-Waist Jeans',
        price: 3999,
        originalPrice: 5999,
        images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80'],
        category: 'jeans',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Dark Blue', 'Black', 'Light Blue'],
        sizes: ['24', '26', '28', '30', '32'],
        stock: 89,
        isActive: true,
        rating: 4.8,
        reviews: 789,
        description: 'Flattering high-waist jeans in stretch denim.'
    },
    {
        _id: 'women-pants-002',
        name: 'Wide Leg Trousers',
        price: 3499,
        originalPrice: 5499,
        images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80'],
        category: 'pants',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Beige', 'Navy'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 56,
        isActive: true,
        rating: 4.7,
        reviews: 345,
        description: 'Elegant wide-leg trousers with pleated front.'
    },
    {
        _id: 'women-pants-003',
        name: 'Leather Leggings',
        price: 4499,
        originalPrice: 6999,
        images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80'],
        category: 'pants',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 43,
        isActive: true,
        rating: 4.6,
        reviews: 234,
        description: 'Faux leather leggings with high waist.'
    },

    // Women's Skirts
    {
        _id: 'women-skirt-001',
        name: 'Pleated Midi Skirt',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80'],
        category: 'skirts',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'Burgundy'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 67,
        isActive: true,
        rating: 4.5,
        reviews: 289,
        description: 'Classic pleated skirt in flowing fabric.'
    },

    // Women's Activewear
    {
        _id: 'women-active-001',
        name: 'Sports Bra',
        price: 1799,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80'],
        category: 'activewear',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'White', 'Pink'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 98,
        isActive: true,
        rating: 4.7,
        reviews: 567,
        description: 'High-support sports bra with moisture-wicking fabric.'
    },
    {
        _id: 'women-active-002',
        name: 'Yoga Leggings',
        price: 2499,
        originalPrice: 3999,
        images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80'],
        category: 'activewear',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'Gray'],
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 123,
        isActive: true,
        rating: 4.8,
        reviews: 890,
        description: 'High-waist yoga leggings with pocket details.'
    },

    // Women's Footwear
    {
        _id: 'women-shoes-001',
        name: 'Ankle Boots',
        price: 5999,
        originalPrice: 8999,
        images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
        category: 'footwear',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Brown'],
        sizes: ['6', '7', '8', '9', '10'],
        stock: 45,
        isActive: true,
        rating: 4.9,
        reviews: 456,
        description: 'Sleek ankle boots with block heel.'
    },
    {
        _id: 'women-shoes-002',
        name: 'White Sneakers',
        price: 4499,
        originalPrice: 6999,
        images: ['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80'],
        category: 'footwear',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['White', 'White/Pink'],
        sizes: ['6', '7', '8', '9'],
        stock: 78,
        isActive: true,
        rating: 4.7,
        reviews: 678,
        description: 'Classic white sneakers with cushioned sole.'
    },

    // Women's Accessories
    {
        _id: 'women-acc-001',
        name: 'Leather Handbag',
        price: 7999,
        originalPrice: 11999,
        images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80'],
        category: 'accessories',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Tan', 'Burgundy'],
        sizes: ['One Size'],
        stock: 34,
        isActive: true,
        rating: 4.8,
        reviews: 345,
        description: 'Structured leather handbag with adjustable strap.'
    },
    {
        _id: 'women-acc-002',
        name: 'Silk Scarf',
        price: 1999,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80'],
        category: 'accessories',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Multi-Pattern'],
        sizes: ['One Size'],
        stock: 89,
        isActive: true,
        rating: 4.6,
        reviews: 234,
        description: 'Luxurious silk scarf with artistic print.'
    },
    {
        _id: 'women-acc-003',
        name: 'Sunglasses',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80'],
        category: 'accessories',
        gender: 'women',
        brand: 'GENWEAR',
        colors: ['Black', 'Tortoise'],
        sizes: ['One Size'],
        stock: 67,
        isActive: true,
        rating: 4.7,
        reviews: 456,
        description: 'Oversized sunglasses with UV protection.'
    },

    // ==================== KIDS' COLLECTION (10 Products) ====================

    {
        _id: 'kids-hoodie-001',
        name: 'Kids Cotton Hoodie',
        price: 1999,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&q=80'],
        category: 'hoodies',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Blue', 'Pink', 'Gray'],
        sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
        stock: 89,
        isActive: true,
        rating: 4.8,
        reviews: 234,
        description: 'Soft cotton hoodie with kangaroo pocket.'
    },
    {
        _id: 'kids-tshirt-001',
        name: 'Kids Graphic Tee',
        price: 999,
        originalPrice: 1499,
        images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80'],
        category: 'tshirts',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['White', 'Black', 'Navy'],
        sizes: ['4Y', '6Y', '8Y', '10Y'],
        stock: 145,
        isActive: true,
        rating: 4.6,
        reviews: 456,
        description: 'Fun graphic tee in soft cotton.'
    },
    {
        _id: 'kids-jeans-001',
        name: 'Kids Denim Jeans',
        price: 1999,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80'],
        category: 'jeans',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Blue', 'Black'],
        sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
        stock: 67,
        isActive: true,
        rating: 4.7,
        reviews: 345,
        description: 'Durable denim jeans with adjustable waist.'
    },
    {
        _id: 'kids-joggers-001',
        name: 'Kids Jogger Set',
        price: 2499,
        originalPrice: 3499,
        images: ['https://images.unsplash.com/photo-1601342701802-98ed06ce0cbc?w=800&q=80'],
        category: 'activewear',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Gray', 'Navy', 'Black'],
        sizes: ['4Y', '6Y', '8Y', '10Y'],
        stock: 54,
        isActive: true,
        rating: 4.5,
        reviews: 234,
        description: 'Matching hoodie and jogger set.'
    },
    {
        _id: 'kids-jacket-001',
        name: 'Kids Puffer Jacket',
        price: 3499,
        originalPrice: 4999,
        images: ['https://images.unsplash.com/photo-1621454523226-eb4f525c8ff7?w=800&q=80'],
        category: 'jackets',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Red', 'Blue', 'Black'],
        sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
        stock: 43,
        isActive: true,
        rating: 4.8,
        reviews: 289,
        description: 'Warm puffer jacket with hood.'
    },
    {
        _id: 'kids-dress-001',
        name: 'Girls Floral Dress',
        price: 2499,
        originalPrice: 3499,
        images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&q=80'],
        category: 'dresses',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Pink Floral', 'Blue Floral'],
        sizes: ['4Y', '6Y', '8Y', '10Y'],
        stock: 38,
        isActive: true,
        rating: 4.7,
        reviews: 178,
        description: 'Pretty floral dress for special occasions.'
    },
    {
        _id: 'kids-shorts-001',
        name: 'Kids Athletic Shorts',
        price: 1299,
        originalPrice: 1999,
        images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80'],
        category: 'activewear',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'Red'],
        sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
        stock: 98,
        isActive: true,
        rating: 4.6,
        reviews: 345,
        description: 'Breathable athletic shorts with elastic waist.'
    },
    {
        _id: 'kids-shoes-001',
        name: 'Kids Sneakers',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800&q=80'],
        category: 'footwear',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['White', 'Black', 'Multi'],
        sizes: ['10', '11', '12', '13', '1', '2', '3'],
        stock: 76,
        isActive: true,
        rating: 4.8,
        reviews: 456,
        description: 'Comfortable sneakers with velcro straps.'
    },
    {
        _id: 'kids-backpack-001',
        name: 'Kids School Backpack',
        price: 1999,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'],
        category: 'accessories',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Blue', 'Pink', 'Black'],
        sizes: ['One Size'],
        stock: 89,
        isActive: true,
        rating: 4.7,
        reviews: 234,
        description: 'Durable backpack with multiple compartments.'
    },
    {
        _id: 'kids-cap-001',
        name: 'Kids Baseball Cap',
        price: 899,
        originalPrice: 1499,
        images: ['https://images.unsplash.com/photo-1588850567054-d82b5456285b?w=800&q=80'],
        category: 'accessories',
        gender: 'kids',
        brand: 'GENWEAR',
        colors: ['Blue', 'Red', 'Black'],
        sizes: ['One Size'],
        stock: 134,
        isActive: true,
        rating: 4.5,
        reviews: 178,
        description: 'Adjustable baseball cap with embroidered logo.'
    },

    // ==================== ACCESSORIES (10 Products) ====================

    {
        _id: 'acc-backpack-001',
        name: 'Urban Backpack',
        price: 3999,
        originalPrice: 5999,
        images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'],
        category: 'bags',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Gray', 'Navy'],
        sizes: ['25L'],
        stock: 67,
        isActive: true,
        rating: 4.8,
        reviews: 456,
        description: 'Waterproof backpack with laptop compartment.'
    },
    {
        _id: 'acc-watch-001',
        name: 'Digital Smart Watch',
        price: 8999,
        originalPrice: 12999,
        images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'],
        category: 'watches',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Silver'],
        sizes: ['44mm'],
        stock: 34,
        isActive: true,
        rating: 4.9,
        reviews: 789,
        isNew: true,
        description: 'Advanced smartwatch with fitness tracking.'
    },
    {
        _id: 'acc-belt-001',
        name: 'Leather Belt',
        price: 1499,
        originalPrice: 2499,
        images: ['https://images.unsplash.com/photo-1624222247344-550fb60583aa?w=800&q=80'],
        category: 'belts',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Brown'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 145,
        isActive: true,
        rating: 4.6,
        reviews: 345,
        description: 'Classic leather belt with metal buckle.'
    },
    {
        _id: 'acc-cap-001',
        name: 'Baseball Cap',
        price: 1299,
        originalPrice: 1999,
        images: ['https://images.unsplash.com/photo-1588850567054-d82b5456285b?w=800&q=80'],
        category: 'caps',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'White'],
        sizes: ['Adjustable'],
        stock: 198,
        isActive: true,
        rating: 4.5,
        reviews: 567,
        description: 'Classic baseball cap with embroidered logo.'
    },
    {
        _id: 'acc-socks-001',
        name: 'Athletic Socks Pack',
        price: 799,
        originalPrice: 1299,
        images: ['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=800&q=80'],
        category: 'socks',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'White', 'Gray'],
        sizes: ['S', 'M', 'L'],
        stock: 267,
        isActive: true,
        rating: 4.7,
        reviews: 890,
        description: 'Pack of 3 cushioned athletic socks.'
    },
    {
        _id: 'acc-beanie-001',
        name: 'Wool Beanie',
        price: 1199,
        originalPrice: 1999,
        images: ['https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=800&q=80'],
        category: 'hats',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Gray', 'Navy'],
        sizes: ['One Size'],
        stock: 156,
        isActive: true,
        rating: 4.6,
        reviews: 234,
        description: 'Warm wool beanie with cuff.'
    },
    {
        _id: 'acc-gloves-001',
        name: 'Touchscreen Gloves',
        price: 1499,
        originalPrice: 2499,
        images: ['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&q=80'],
        category: 'gloves',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Gray'],
        sizes: ['S', 'M', 'L'],
        stock: 89,
        isActive: true,
        rating: 4.7,
        reviews: 345,
        description: 'Warm gloves with touchscreen-compatible fingertips.'
    },
    {
        _id: 'acc-tie-001',
        name: 'Silk Necktie',
        price: 1799,
        originalPrice: 2999,
        images: ['https://images.unsplash.com/photo-1598033129183-c4f50c7176c8?w=800&q=80'],
        category: 'ties',
        gender: 'men',
        brand: 'GENWEAR',
        colors: ['Navy', 'Burgundy', 'Black'],
        sizes: ['One Size'],
        stock: 123,
        isActive: true,
        rating: 4.5,
        reviews: 178,
        description: 'Premium silk tie with subtle pattern.'
    },
    {
        _id: 'acc-messenger-001',
        name: 'Messenger Bag',
        price: 4499,
        originalPrice: 6999,
        images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80'],
        category: 'bags',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Brown'],
        sizes: ['15L'],
        stock: 45,
        isActive: true,
        rating: 4.8,
        reviews: 289,
        description: 'Canvas messenger bag with leather trim.'
    },
    {
        _id: 'acc-gym-bag-001',
        name: 'Gym Duffel Bag',
        price: 2999,
        originalPrice: 4499,
        images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'],
        category: 'bags',
        gender: 'unisex',
        brand: 'GENWEAR',
        colors: ['Black', 'Navy', 'Gray'],
        sizes: ['40L'],
        stock: 78,
        isActive: true,
        rating: 4.7,
        reviews: 456,
        description: 'Spacious duffel bag with shoe compartment.'
    }
];

export default ENHANCED_PRODUCTS;
